name: myDrive Docker CI

on:
  push:
    branches: [ mydrive-GithubActions ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Import GPG Key
      run: |
          set -x
          cat <(echo -e "${{ secrets.GPG_SIGNING_KEY }}") | gpg --import --no-tty --batch --yes
          gpg --list-secret-keys --keyid-format LONG
          gpg -v --quiet --yes --decrypt --passphrase=${{ secrets.GPG_PASSPHRASE }} --output docker-variables.env docker-variables.env.gpg
    - name: Create volume for Mongo
      run: docker volume create --name=mongodb_data_volume
    - name: Build the Docker image
      run: docker-compose build
