name: myDrive Docker CI

on:
  push:
    branches: [ mydrive-GithubActions ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create volume for Mongo
      run: docker volume create --name=mongodb_data_volume
    - name: Build the Docker image
      run: docker-compose build
    - name: Container run
      run: docker-compose up -d
    - name: Test
      run: docker exec -it mydrive-node curl -s --retry 10 --retry-connrefused http://localhost:3000/
