name: myDrive Docker CI

on:
  push:
    branches: [ mydrive-GithubActions ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Import GPG Key
      env:
         GPG_PRIVATE_KEY: ${{ secrets.GPG_SIGNING_KEY }}
         PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      run: |
          echo -n "$GPG_PRIVATE_KEY" | base64 --decode | gpg --import
          gpg --quiet --batch --yes --decrypt --passphrase=$env:GPG_PASSPHRASE --output docker-variables.env docker-variables.env.gpg
    - name: Create volume for Mongo
      run: docker volume create --name=mongodb_data_volume
    - name: Build the Docker image
      run: docker-compose build
    - name: Container run
      run: docker-compose up -d
