name: myDrive Docker CI

on:
  push:
    branches: [ mydrive-GithubActions ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Import GPG key
      id: import_gpg
      uses: hashicorp/ghaction-import-gpg@v2.1.0
      env:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_SIGNING_KEY }}
        PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
    - run: |
          gpg -v --quiet --yes --decrypt --passphrase=${{ secrets.GPG_PASSPHRASE }} --output docker-variables.env docker-variables.env.gpg
    - name: Create volume for Mongo
      run: docker volume create --name=mongodb_data_volume
    - name: Build the Docker image and push to registry
      run: | 
          docker-compose build
          echo ${{ secrets.PAT }} | docker login ghcr.io --username vitstef --password-stdin
          docker tag mydrive_app ghcr.io/vitstef/mydrive_app:latest
          docker push ghcr.io/vitstef/mydrive_app:latest
